import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Lock, PlayCircle } from 'lucide-react';
import AcademyTutor from './AcademyTutor';
import './academyLessonExperience.css';
const courseId='hlabi-property-professional-foundation';
const api=(path:string,options?:RequestInit)=>fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});
type Enrollment={id:string;status:string;progressPercent:number;completedModules:number};
type Asset={id:string;kind:'TEXT'|'VIDEO'|'AUDIO'|'SIMULATION'|'REFERENCE';title:string;description:string;uri:string;required:boolean;durationSeconds?:number};
type Lesson={id:string;courseId:string;moduleIndex:number;lessonIndex:number;title:string;objective:string;assets:Asset[];assessmentId:string;passingScore:number;status:string;assessmentPassed:boolean;canAdvance:boolean;requiredAssetsCompleted:string[];learningComplete:boolean};
type Assessment={id:string;moduleIndex:number;title:string;kind:string;passingScore:number;questions:{id:string;prompt:string;options?:string[];points:number;kind:string}[];rubric:string[]};
type Attempt={assessmentId:string;status:string;score:number|null;maxScore:number;feedback?:string};
export default function AcademyLessonExperience(){
 const [enrollment,setEnrollment]=useState<Enrollment|null>(null);const [lessons,setLessons]=useState<Lesson[]>([]);const [assessments,setAssessments]=useState<Assessment[]>([]);const [attempts,setAttempts]=useState<Attempt[]>([]);const [selected,setSelected]=useState<Lesson|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const current=useMemo(()=>lessons.find(l=>l.moduleIndex===(enrollment?.completedModules??0))??null,[lessons,enrollment]);
 const refresh=async()=>{const er=await api('/api/v1/academy/enrollments');if(!er.ok)return;const rows=await er.json();if(!rows[0])return;const e=rows[0] as Enrollment;setEnrollment(e);const [lr,ar,tr]=await Promise.all([api(`/api/v1/academy/enrollments/${e.id}/lessons`),api(`/api/v1/academy/enrollments/${e.id}/assessments`),api(`/api/v1/academy/enrollments/${e.id}/assessment-attempts`)]);if(lr.ok){const nextLessons=await lr.json();setLessons(nextLessons);if(selected){const updated=nextLessons.find((l:Lesson)=>l.id===selected.id);if(updated)setSelected(updated);}}if(ar.ok)setAssessments(await ar.json());if(tr.ok)setAttempts(await tr.json());};
 useEffect(()=>{refresh().catch(()=>{});},[]);
 const start=async()=>{setMessage('');const r=await api('/api/v1/academy/enrollments',{method:'POST',body:JSON.stringify({courseId})});if(!r.ok){setMessage('Unable to start Academy right now.');return}await refresh();};
 const openLesson=async(lesson:Lesson)=>{if(lesson.status==='LOCKED'){setMessage(`Lesson ${lesson.moduleIndex+1} is locked. Complete the current lesson first.`);return}setSelected(lesson);setMessage('');};
 const markAsset=async(asset:Asset)=>{if(!selected||busy||selected.requiredAssetsCompleted.includes(asset.id))return;setBusy(true);const r=await api(`/api/v1/academy/enrollments/${enrollment?.id}/lessons/${selected.moduleIndex}/assets/${asset.id}/activity`,{method:'POST',body:JSON.stringify({eventType:'COMPLETED'})});const body=await r.json().catch(()=>({}));if(!r.ok)setMessage(body.error==='LESSON_LOCKED'?'This lesson is locked.':'Learning activity could not be recorded.');else{setMessage(`${asset.kind} learning activity recorded.`);await refresh();}setBusy(false);};
 const submitAssessment=async()=>{if(!selected||!enrollment||busy)return;const assessment=assessments.find(a=>a.id===selected.assessmentId);if(!assessment)return;if(!selected.learningComplete){setMessage('Complete all required learning activity before the assessment.');return}if(assessment.questions.some(q=>!answers[q.id]?.trim())){setMessage('Complete every assessment question before submitting.');return}setBusy(true);setMessage('');const r=await api(`/api/v1/academy/enrollments/${enrollment.id}/assessment-attempts`,{method:'POST',body:JSON.stringify({assessmentId:assessment.id,answers})});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(body.error==='SEQUENTIAL_PROGRESS_REQUIRED'?'This assessment is locked until you reach this lesson.':body.error==='ASSESSMENT_AWAITING_REVIEW'?'Your previous practical submission is awaiting authorised review.':'Assessment submission could not be recorded.');}else{setMessage(body.status==='PASSED'?'Assessment passed. The next lesson is now available.':body.status==='NEEDS_REVIEW'?'Submitted for authorised review.':'Assessment failed. Review the feedback and retry.');setAnswers({});await refresh();}setBusy(false);};
 const latest=selected?[...attempts].reverse().find(a=>a.assessmentId===selected.assessmentId):undefined;const canAdvance=Boolean(selected?.learningComplete&&latest?.status==='PASSED');
 const advance=async()=>{if(!selected||!enrollment||!canAdvance)return;setBusy(true);const r=await api(`/api/v1/academy/enrollments/${enrollment.id}/progress`,{method:'POST',body:JSON.stringify({moduleIndex:selected.moduleIndex,eventType:'MODULE_COMPLETED',payload:{source:'academy-lesson-experience',lessonId:selected.id}})});const body=await r.json().catch(()=>({}));if(!r.ok)setMessage(body.error==='LEARNING_CONTENT_REQUIRED'?'Complete all required lesson content before advancing.':body.error==='ASSESSMENT_PASS_REQUIRED'?'Pass the lesson assessment before advancing.':'The lesson cannot be advanced yet.');else{setMessage('Lesson completed. Next lesson unlocked.');setSelected(null);await refresh();}setBusy(false);};
 return <section className="academy-lesson-experience"><div className="academy-lesson-header"><div><p className="eyebrow">HLABI ACADEMY · LESSON EXPERIENCE</p><h2>Learn → Practise → Prove → Advance</h2><p>Every lesson is a controlled progression. Required learning comes first, then the assessment checkpoint, then the next lesson.</p></div>{enrollment?<div className="academy-lesson-progress"><strong>{enrollment.progressPercent}%</strong><span>{enrollment.completedModules} of {lessons.length} lessons completed</span></div>:<button className="primary" onClick={start}>Start Academy <ArrowRight size={17}/></button>}</div>
 <div className="academy-lesson-list">{lessons.map(lesson=>{const active=lesson.moduleIndex===(enrollment?.completedModules??0);const done=lesson.status==='PASSED'||lesson.moduleIndex<(enrollment?.completedModules??0);return <button key={lesson.id} className={`academy-lesson-row ${done?'done':''} ${active?'active':''}`} onClick={()=>openLesson(lesson)}><span className="academy-lesson-number">{done?<CheckCircle2 size={17}/>:lesson.status==='LOCKED'?<Lock size={16}/>:<PlayCircle size={17}/>}</span><span><small>LESSON {String(lesson.moduleIndex+1).padStart(2,'0')}</small><strong>{lesson.title}</strong><em>{lesson.objective}</em></span><ArrowRight size={16}/></button>})}</div>
 {selected&&<div className="academy-lesson-workspace"><div className="academy-lesson-workspace-head"><div><p className="eyebrow">LESSON {String(selected.moduleIndex+1).padStart(2,'0')}</p><h3>{selected.title}</h3><p>{selected.objective}</p></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="academy-asset-grid">{selected.assets.map(asset=>{const complete=selected.requiredAssetsCompleted.includes(asset.id);return <article className={`academy-asset ${complete?'complete':''}`} key={asset.id}><div><span>{asset.kind}</span>{asset.required&&<b>REQUIRED</b>}</div><h4>{asset.title}</h4><p>{asset.description}</p>{asset.durationSeconds&&<small>{Math.ceil(asset.durationSeconds/60)} min</small>}{asset.kind==='VIDEO'&&<video controls preload="metadata" src={asset.uri} aria-label={asset.title} style={{width:'100%',borderRadius:12}}/>}{asset.kind==='AUDIO'&&<audio controls preload="metadata" src={asset.uri} aria-label={asset.title} style={{width:'100%'}}/>}<button onClick={()=>markAsset(asset)} disabled={complete||busy}>{complete?'Completed':'Complete learning activity'} {complete?<CheckCircle2 size={14}/>:<ArrowRight size={14}/>}</button></article>})}</div><div className="academy-checkpoint"><div><p className="eyebrow">ASSESSMENT CHECKPOINT</p><strong>{assessments.find(a=>a.id===selected.assessmentId)?.title??'Lesson assessment'}</strong><span>Pass mark: {selected.passingScore}% · required before advancement</span></div><div className="academy-attempt-summary">{latest&&<span className={latest.status==='PASSED'?'passed':latest.status==='FAILED'?'failed':'pending'}>{latest.status}{latest.score!==null?` · ${latest.score}/${latest.maxScore}`:''}</span>}</div></div><AcademyTutor enrollmentId={enrollment?.id} moduleIndex={selected.moduleIndex}/>{(()=>{const a=assessments.find(x=>x.id===selected.assessmentId);if(!a)return null;return <div className="academy-lesson-assessment">{a.questions.map(q=><div className="academy-question" key={q.id}><strong>{q.prompt}</strong>{q.options?.length?<div className="academy-options">{q.options.map(o=><label key={o}><input type="radio" name={q.id} checked={answers[q.id]===o} onChange={()=>setAnswers({...answers,[q.id]:o})}/><span>{o}</span></label>)}</div>:<textarea value={answers[q.id]??''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} placeholder="Write your response..."/>}</div>)}{a.rubric.length>0&&<div className="academy-rubric"><b>Review criteria</b>{a.rubric.map(r=><small key={r}>• {r}</small>)}</div>}<div className="academy-lesson-actions"><button className="primary" onClick={submitAssessment} disabled={busy||!selected.learningComplete}>Submit assessment</button><button className="secondary" onClick={advance} disabled={busy||!canAdvance}>Advance lesson</button></div></div>})()}</div>}
 {message&&<div className="academy-action-message">{message}</div>}</section>;
}
