import { useState } from 'react';
import { ArrowRight, CheckCircle2, KeyRound, Store, TrendingUp, X } from 'lucide-react';

type JourneyKey = 'BUYER' | 'SELLER' | 'INVESTOR';
const journeyConfig: Record<JourneyKey, { title: string; intro: string; steps: string[]; prompts: string[] }> = {
  BUYER: { title: 'Buying a home', intro: 'Tell us what you are looking for and build a guided path from search to ownership.', steps: ['Define your budget and priorities', 'Discover suitable properties', 'Arrange viewings and due diligence', 'Plan your move and ongoing ownership'], prompts: ['Preferred area or areas', 'Approximate budget', 'Property type', 'What matters most to you?'] },
  SELLER: { title: 'Selling a property', intro: 'Prepare the property, understand the selling journey and keep the important work connected.', steps: ['Capture property details', 'Review condition and preparation needs', 'Prepare the listing and buyer journey', 'Track offers, transfer and next steps'], prompts: ['Property location', 'Property type', 'Expected timing', 'What would you like help with first?'] },
  INVESTOR: { title: 'Property investing', intro: 'Organise investment objectives, opportunities and ownership services in one property workspace.', steps: ['Define investment objectives', 'Capture target areas and criteria', 'Review opportunities and property information', 'Plan acquisition and ongoing property operations'], prompts: ['Target area', 'Investment budget', 'Property strategy', 'What are you optimising for?'] },
};
export default function JourneyExplorer() { const [selected,setSelected]=useState<JourneyKey|null>(null); const [submitted,setSubmitted]=useState(false); const config=selected?journeyConfig[selected]:null; const close=()=>setSelected(null); return <>
  <div className="journey-grid journey-grid-featured">
    <article className="journey journey-featured" onClick={()=>{setSelected('BUYER');setSubmitted(false)}}><KeyRound size={24}/><span className="journey-kicker">BUY</span><h3>I want to buy</h3><p>Build a guided path from your search criteria through viewing, due diligence and ownership.</p><button>Start buying <ArrowRight size={15}/></button></article>
    <article className="journey journey-featured" onClick={()=>{setSelected('SELLER');setSubmitted(false)}}><Store size={24}/><span className="journey-kicker">SELL</span><h3>I want to sell</h3><p>Prepare your property, organise the selling journey and connect the people needed to move forward.</p><button>Start selling <ArrowRight size={15}/></button></article>
    <article className="journey journey-featured" onClick={()=>{setSelected('INVESTOR');setSubmitted(false)}}><TrendingUp size={24}/><span className="journey-kicker">INVEST</span><h3>I’m an investor</h3><p>Organise investment criteria, opportunities and long-term property operations in one place.</p><button>Explore investing <ArrowRight size={15}/></button></article>
  </div>
  {config&&<div className="journey-overlay" role="dialog" aria-modal="true" aria-label={config.title}><div className="journey-modal"><button className="journey-close" onClick={close} aria-label="Close"><X size={20}/></button>{!submitted?<><p className="eyebrow">YOUR PROPERTY JOURNEY</p><h2>{config.title}</h2><p className="journey-modal-intro">{config.intro}</p><div className="journey-plan">{config.steps.map((step,i)=><div key={step}><b>0{i+1}</b><span>{step}</span></div>)}</div><div className="journey-intake"><h3>Start with a few details</h3>{config.prompts.map(prompt=><label key={prompt}>{prompt}<input placeholder="Your answer"/></label>)}</div><button className="primary journey-submit" onClick={()=>setSubmitted(true)}>Create my journey <ArrowRight size={18}/></button><small className="journey-note">This is a planning intake, not a credit, valuation, legal, tax or investment recommendation.</small></>:<div className="journey-success"><CheckCircle2 size={42}/><p className="eyebrow">JOURNEY CREATED</p><h2>You have a starting point.</h2><p>Next, the Hub can connect the relevant property services, people and tools to your journey.</p><button className="primary" onClick={close}>Continue <ArrowRight size={18}/></button></div>}</div></div>}
</> }
