import {FormEvent,useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2} from 'lucide-react';

type Listing={id:string;propertyId:string;status:string;title:string;description:string;askingPriceCents?:number;bedrooms?:number;bathrooms?:number;features:string[]};
export default function SellerListingWorkspace({propertyId}:{propertyId:string}){
 const [listing,setListing]=useState<Listing|null>(null); const [form,setForm]=useState({title:'',description:'',askingPrice:'',bedrooms:'',bathrooms:'',features:''}); const [status,setStatus]=useState('loading'); const [message,setMessage]=useState('');
 const load=async()=>{const r=await fetch('/api/v1/seller/properties/'+encodeURIComponent(propertyId)+'/listing');if(r.status===404){setStatus('new');return;}if(!r.ok){setStatus('error');setMessage('Unable to load listing workspace.');return;}const x=await r.json();setListing(x);setForm({title:x.title,description:x.description,askingPrice:x.askingPriceCents?String(x.askingPriceCents/100):'',bedrooms:x.bedrooms==null?'':String(x.bedrooms),bathrooms:x.bathrooms==null?'':String(x.bathrooms),features:(x.features||[]).join(', ')});setStatus('ready');};
 useEffect(()=>{load();},[propertyId]);
 const save=async(e:FormEvent)=>{e.preventDefault();setStatus('saving');setMessage('');const body={title:form.title,description:form.description,askingPriceCents:form.askingPrice?Math.round(Number(form.askingPrice)*100):undefined,bedrooms:form.bedrooms?Number(form.bedrooms):undefined,bathrooms:form.bathrooms?Number(form.bathrooms):undefined,features:form.features.split(',').map(x=>x.trim()).filter(Boolean),status:'READY_TO_LIST'};const r=await fetch('/api/v1/seller/properties/'+encodeURIComponent(propertyId)+'/listing',{method:listing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){setStatus('error');setMessage((await r.json()).error||'Unable to save listing.');return;}setListing(await r.json());setStatus('ready');setMessage('Listing preparation saved.');};
 const publish=async()=>{setStatus('saving');const r=await fetch('/api/v1/seller/properties/'+encodeURIComponent(propertyId)+'/listing/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})});if(!r.ok){setStatus('error');setMessage((await r.json()).error||'Unable to publish listing.');return;}setListing(await r.json());setStatus('ready');setMessage('Listing is now live.');};
 if(status==='loading')return <div className="journey-next">Loading listing workspace…</div>;
 return <section className="journey-listing-workspace"><div className="section-head"><div><p className="eyebrow">SELLER WORKSPACE</p><h3>Prepare the listing</h3></div>{listing&&<span>{listing.status.replaceAll('_',' ')}</span>}</div><form onSubmit={save}><label>Listing title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Light-filled family home near..." required/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the property accurately for prospective buyers." minLength={20} required/></label><label>Asking price (R)<input type="number" min="1" value={form.askingPrice} onChange={e=>setForm({...form,askingPrice:e.target.value})}/></label><div><label>Bedrooms<input type="number" min="0" value={form.bedrooms} onChange={e=>setForm({...form,bedrooms:e.target.value})}/></label><label>Bathrooms<input type="number" min="0" step="0.5" value={form.bathrooms} onChange={e=>setForm({...form,bathrooms:e.target.value})}/></label></div><label>Features<input value={form.features} onChange={e=>setForm({...form,features:e.target.value})} placeholder="Garden, garage, solar,..." /></label><button className="primary" disabled={status==='saving'}>{status==='saving'?'Saving…':'Save & mark ready'} <ArrowRight size={16}/></button></form>{message&&<p role="alert">{message}</p>}{listing?.status==='READY_TO_LIST'&&<button className="secondary" onClick={publish} disabled={status==='saving'}><CheckCircle2 size={16}/> Confirm & publish listing</button>} {listing?.status==='LISTED'&&<p className="journey-note">This listing is live in the buyer/investor discovery feed. Viewing, lead and offer workflows come next.</p>}</section>;
}
