import {useEffect,useState} from 'react';
import {CheckCircle2,FileText,RefreshCw,ShieldCheck} from 'lucide-react';

type Transaction={id:string;status:string;buyerId:string;sellerId:string;agentId?:string;createdAt:string;completedAt?:string;milestones:{id:string;key:string;label:string;status:string;notes?:string}[];documents:{id:string;kind:string;label:string;status:string;storageKey?:string;notes?:string}[];audit:{id:string;eventType:string;actorId:string;createdAt:string}[]};
const labels:Record<string,string>={OFFER_ACCEPTANCE:'Offer acceptance',IDENTITY:'Identity documents',FINANCE:'Finance / proof of funds',COMPLIANCE:'Compliance documents',TRANSFER:'Transfer / registration documents',OTHER:'Other transaction documents'};
export default function TransactionWorkspace(){
 const [items,setItems]=useState<Transaction[]>([]);const [selected,setSelected]=useState<Transaction|null>(null);const [status,setStatus]=useState('loading');const [message,setMessage]=useState('');
 const load=async()=>{setStatus('loading');const r=await fetch('/api/v1/transactions');if(!r.ok){setStatus('error');setMessage('Sign in with a buyer, seller or agent account to view transactions.');return;}const x=await r.json();setItems(x);if(x[0])await open(x[0].id);else setStatus('ready');};
 const open=async(id:string)=>{const r=await fetch('/api/v1/transactions/'+encodeURIComponent(id));if(!r.ok){setMessage('Unable to load transaction.');return;}setSelected(await r.json());setStatus('ready');};
 useEffect(()=>{load()},[]);
 const updateStatus=async(next:string)=>{if(!selected)return;const r=await fetch('/api/v1/transactions/'+selected.id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next,confirm:true})});if(!r.ok){setMessage((await r.json()).error||'Unable to update transaction.');return;}setMessage('Transaction status updated.');await open(selected.id);};
 const updateMilestone=async(id:string,next:string)=>{if(!selected)return;const r=await fetch('/api/v1/transactions/'+selected.id+'/milestones/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});if(!r.ok){setMessage((await r.json()).error||'Unable to update milestone.');return;}await open(selected.id);};
 if(status==='loading')return <section className="shell"><p>Loading transaction workspace…</p></section>;
 return <section className="shell" id="transactions"><div className="section-head"><div><p className="eyebrow">TRANSACTION WORKSPACE</p><h2>Move from accepted offer to completion.</h2></div><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{message&&<p role="alert">{message}</p>}{!items.length?<div className="journey-next">No active transactions are attached to this account yet.</div>:<div className="two-col"><div>{items.map(x=><button key={x.id} className="journey" onClick={()=>open(x.id)}><b>{x.status.replaceAll('_',' ')}</b><span>Transaction {x.id.slice(0,8)}</span><small>{new Date(x.createdAt).toLocaleDateString()}</small></button>)}</div>{selected&&<article className="journey-listing-workspace"><div className="section-head"><div><p className="eyebrow">TRANSACTION {selected.id.slice(0,8)}</p><h3>{selected.status.replaceAll('_',' ')}</h3></div><ShieldCheck size={24}/></div><div className="journey-plan">{selected.milestones.map(m=><div key={m.id}><b>{m.status==='COMPLETED'?'✓':'•'}</b><span>{m.label}</span><select value={m.status} onChange={e=>updateMilestone(m.id,e.target.value)}><option>PENDING</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>BLOCKED</option></select></div>)}</div><h3><FileText size={18}/> Documents</h3><div>{selected.documents.map(d=><div className="journey-next" key={d.id}><b>{d.label||labels[d.kind]||d.kind}</b><span>{d.status.replaceAll('_',' ')}</span></div>)}</div>{selected.status==='OPEN'&&<button className="secondary" onClick={()=>updateStatus('CONDITIONAL')}>Mark conditional</button>}{selected.status==='CONDITIONAL'&&<button className="secondary" onClick={()=>updateStatus('IN_TRANSFER')}>Move to transfer</button>}{selected.status==='IN_TRANSFER'&&<button className="primary" onClick={()=>updateStatus('COMPLETED')}><CheckCircle2 size={16}/> Confirm completion</button>}</article>}</div>}</section>;
}