import { z } from 'zod';
import type { Express, RequestHandler } from 'express';
import { authenticatedPrincipal } from './authentication.js';
import type { AcademyRepository } from './academyRepository.js';
import { MemoryAcademyReadinessExamRepository } from './academyReadinessExamRepository.js';
import type { AcademyReadinessExamRepository } from './academyReadinessExamRepository.js';
import { ACADEMY_READINESS_EXAM } from './academyReadinessExam.js';
import { ACADEMY_READINESS_EXAM_QUESTIONS, READINESS_EXAM_MAX_SCORE, publicReadinessExamQuestion } from './academyReadinessExamQuestionBank.js';

const defaultExamRepository=new MemoryAcademyReadinessExamRepository();
export function registerAcademyReadinessExamRoutes(app:Express,authenticated:RequestHandler,academyRepo:AcademyRepository,examRepo:AcademyReadinessExamRepository=defaultExamRepository){
 const answersSchema=z.record(z.string().max(10000));
 const reviewerSchema=z.object({score:z.number().min(0).max(100),status:z.enum(['PASSED','FAILED']),feedback:z.string().min(1).max(5000)});
 app.get('/api/v1/academy/enrollments/:enrollmentId/readiness-exam',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academyRepo.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});return res.json({exam:ACADEMY_READINESS_EXAM,questionBankVersion:ACADEMY_READINESS_EXAM.version,maxScore:READINESS_EXAM_MAX_SCORE,attempts:await examRepo.list(e.id,p.userId)});});
 app.post('/api/v1/academy/enrollments/:enrollmentId/readiness-exam/start',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academyRepo.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});if(e.completedModules<6)return res.status(409).json({error:'FOUNDATION_COMPLETION_REQUIRED',message:'Complete all Foundation lessons and assessments before starting the readiness examination.'});const existing=await examRepo.list(e.id,p.userId);const active=existing.find(a=>a.status==='IN_PROGRESS');if(active)return res.json({attempt:active,questions:ACADEMY_READINESS_EXAM_QUESTIONS.map(publicReadinessExamQuestion)});const prior=existing.find(a=>a.status==='PASSED');if(prior)return res.status(409).json({error:'READINESS_EXAM_ALREADY_PASSED'});const attempt=await examRepo.create({enrollmentId:e.id,userId:p.userId,examVersion:ACADEMY_READINESS_EXAM.version,status:'IN_PROGRESS',answers:{},score:null,maxScore:READINESS_EXAM_MAX_SCORE});return res.status(201).json({attempt,exam:ACADEMY_READINESS_EXAM,questions:ACADEMY_READINESS_EXAM_QUESTIONS.map(publicReadinessExamQuestion)});});
 app.post('/api/v1/academy/enrollments/:enrollmentId/readiness-exam/:attemptId/submit',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academyRepo.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});const attempt=await examRepo.get(req.params.attemptId,p.userId);if(!attempt||attempt.enrollmentId!==e.id)return res.status(404).json({error:'EXAM_ATTEMPT_NOT_FOUND'});if(attempt.status!=='IN_PROGRESS')return res.status(409).json({error:'EXAM_ATTEMPT_NOT_OPEN'});const parsed=answersSchema.safeParse(req.body?.answers);if(!parsed.success)return res.status(400).json({error:'INVALID_EXAM_ANSWERS',details:parsed.error.flatten()});if(Date.now()-new Date(attempt.startedAt).getTime()>ACADEMY_READINESS_EXAM.durationMinutes*60*1000)return res.status(409).json({error:'EXAM_TIME_EXPIRED'});const answers=parsed.data;const ids=ACADEMY_READINESS_EXAM_QUESTIONS.map(q=>q.id);if(Object.keys(answers).some(id=>!ids.includes(id))||ids.some(id=>!answers[id]?.trim()))return res.status(400).json({error:'INCOMPLETE_EXAM'});let objectiveScore=0;let reviewedMax=0;for(const q of ACADEMY_READINESS_EXAM_QUESTIONS){if(q.kind==='KNOWLEDGE'&&answers[q.id]===q.correctAnswer)objectiveScore+=q.points;if(q.kind==='SIMULATION')reviewedMax+=q.points;}const status=reviewedMax?'NEEDS_REVIEW':objectiveScore/READINESS_EXAM_MAX_SCORE*100>=ACADEMY_READINESS_EXAM.passingScore?'PASSED':'FAILED';const score=reviewedMax?null:objectiveScore/READINESS_EXAM_MAX_SCORE*100;const updated=await examRepo.submit(attempt.id,p.userId,answers,score,status);return res.json({attempt:updated,objectiveScore,reviewRequired:Boolean(reviewedMax),reviewedPoints:reviewedMax});});
 app.get('/api/v1/academy/reviewer/readiness-exams',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(!['ACADEMY_REVIEWER','ADMIN'].includes(p.role))return res.status(403).json({error:'ROLE_NOT_ALLOWED'});return res.json(await examRepo.listPendingReview());});
 app.post('/api/v1/academy/reviewer/readiness-exams/:attemptId/review',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(!['ACADEMY_REVIEWER','ADMIN'].includes(p.role))return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const parsed=reviewerSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_REVIEW',details:parsed.error.flatten()});const attempt=await examRepo.review(req.params.attemptId,p.userId,parsed.data.score,parsed.data.status,parsed.data.feedback);if(!attempt)return res.status(404).json({error:'EXAM_REVIEW_NOT_AVAILABLE'});return res.json(attempt);});
}
