export const ACADEMY_LESSON_SCHEMA='hlabi.academy.lesson.v1';
export type AcademyLessonStatus='LOCKED'|'AVAILABLE'|'IN_PROGRESS'|'ASSESSMENT_REQUIRED'|'PASSED';
export type AcademyLessonAssetKind='TEXT'|'VIDEO'|'AUDIO'|'SIMULATION'|'REFERENCE';
export interface AcademyLessonAsset { id:string; kind:AcademyLessonAssetKind; title:string; description:string; uri:string; required:boolean; durationSeconds?:number; }
export interface AcademyLesson { id:string; courseId:string; moduleIndex:number; lessonIndex:number; title:string; objective:string; assets:AcademyLessonAsset[]; assessmentId:string; passingScore:number; }
export const ACADEMY_LESSONS:AcademyLesson[]=[
 {id:'foundation-lesson-01',courseId:'hlabi-property-professional-foundation',moduleIndex:0,lessonIndex:0,title:'Property fundamentals: the professional role',objective:'Build a working foundation in property practice, responsibilities and the professional environment.',assessmentId:'module-0-knowledge',passingScore:70,assets:[{id:'foundation-01-text',kind:'TEXT',title:'Core lesson',description:'Authoritative written lesson and reference material.',uri:'academy://foundation/module-0/lesson-0/text',required:true},{id:'foundation-01-video',kind:'VIDEO',title:'Instructor walkthrough',description:'Video explanation of the lesson concepts.',uri:'academy://foundation/module-0/lesson-0/video',required:false},{id:'foundation-01-audio',kind:'AUDIO',title:'Audio revision',description:'Concise audio revision of the lesson.',uri:'academy://foundation/module-0/lesson-0/audio',required:false}]},
 {id:'foundation-lesson-02',courseId:'hlabi-property-professional-foundation',moduleIndex:1,lessonIndex:0,title:'Buyer and seller journeys',objective:'Understand client requirements, affordability, consent and traceable next steps.',assessmentId:'module-1-simulation',passingScore:70,assets:[{id:'foundation-02-text',kind:'TEXT',title:'Core lesson',description:'Buyer and seller journey reference material.',uri:'academy://foundation/module-1/lesson-0/text',required:true},{id:'foundation-02-video',kind:'VIDEO',title:'Journey walkthrough',description:'Scenario walkthrough from enquiry to next action.',uri:'academy://foundation/module-1/lesson-0/video',required:false},{id:'foundation-02-audio',kind:'AUDIO',title:'Audio revision',description:'Concise journey revision.',uri:'academy://foundation/module-1/lesson-0/audio',required:false}]},
 {id:'foundation-lesson-03',courseId:'hlabi-property-professional-foundation',moduleIndex:2,lessonIndex:0,title:'Listing, marketing and compliance',objective:'Apply material-information, disclosure and marketing principles.',assessmentId:'module-2-knowledge',passingScore:70,assets:[{id:'foundation-03-text',kind:'TEXT',title:'Core lesson',description:'Listing, marketing and compliance reference material.',uri:'academy://foundation/module-2/lesson-0/text',required:true},{id:'foundation-03-video',kind:'VIDEO',title:'Listing walkthrough',description:'Practical listing and marketing demonstration.',uri:'academy://foundation/module-2/lesson-0/video',required:false},{id:'foundation-03-audio',kind:'AUDIO',title:'Audio revision',description:'Concise compliance revision.',uri:'academy://foundation/module-2/lesson-0/audio',required:false}]},
 {id:'foundation-lesson-04',courseId:'hlabi-property-professional-foundation',moduleIndex:3,lessonIndex:0,title:'Negotiation and professional judgement',objective:'Practise authority, confidentiality, competing priorities and auditable next steps.',assessmentId:'module-3-simulation',passingScore:70,assets:[{id:'foundation-04-text',kind:'TEXT',title:'Core lesson',description:'Negotiation and judgement reference material.',uri:'academy://foundation/module-3/lesson-0/text',required:true},{id:'foundation-04-video',kind:'VIDEO',title:'Negotiation case',description:'Case walkthrough showing professional judgement in practice.',uri:'academy://foundation/module-3/lesson-0/video',required:false},{id:'foundation-04-audio',kind:'AUDIO',title:'Audio revision',description:'Concise judgement revision.',uri:'academy://foundation/module-3/lesson-0/audio',required:false}]},
 {id:'foundation-lesson-05',courseId:'hlabi-property-professional-foundation',moduleIndex:4,lessonIndex:0,title:'Ethics, compliance and professional conduct',objective:'Apply ethical duties, conflict handling, authority, records and escalation.',assessmentId:'module-4-knowledge',passingScore:70,assets:[{id:'foundation-05-text',kind:'TEXT',title:'Core lesson',description:'Ethics and compliance reference material.',uri:'academy://foundation/module-4/lesson-0/text',required:true},{id:'foundation-05-video',kind:'VIDEO',title:'Ethics case walkthrough',description:'Applied professional-conduct scenarios.',uri:'academy://foundation/module-4/lesson-0/video',required:false},{id:'foundation-05-audio',kind:'AUDIO',title:'Audio revision',description:'Concise ethics revision.',uri:'academy://foundation/module-4/lesson-0/audio',required:false}]},
 {id:'foundation-lesson-06',courseId:'hlabi-property-professional-foundation',moduleIndex:5,lessonIndex:0,title:'AI-assisted property practice',objective:'Use AI while verifying outputs, protecting information and retaining human accountability.',assessmentId:'module-5-simulation',passingScore:70,assets:[{id:'foundation-06-text',kind:'TEXT',title:'Core lesson',description:'AI-assisted property practice reference material.',uri:'academy://foundation/module-5/lesson-0/text',required:true},{id:'foundation-06-video',kind:'VIDEO',title:'AI workflow demonstration',description:'Demonstration of verification and accountable AI use.',uri:'academy://foundation/module-5/lesson-0/video',required:false},{id:'foundation-06-audio',kind:'AUDIO',title:'Audio revision',description:'Concise AI-practice revision.',uri:'academy://foundation/module-5/lesson-0/audio',required:false}]}
];
export function academyLessonForModule(moduleIndex:number){return ACADEMY_LESSONS.find(l=>l.moduleIndex===moduleIndex)??null;}
