import { randomUUID } from 'node:crypto';
import type { AcademyCourse, AcademyEnrollment, AcademyEnrollmentStatus, AcademyProgressEvent } from './academyDomain.js';
export interface AcademyRepository { listCourses():Promise<AcademyCourse[]>; getCourse(id:string):Promise<AcademyCourse|null>; enroll(input:{userId:string;courseId:string}):Promise<AcademyEnrollment>; getEnrollment(id:string,userId:string):Promise<AcademyEnrollment|null>; listEnrollments(userId:string):Promise<AcademyEnrollment[]>; recordProgress(input:{enrollmentId:string;userId:string;moduleIndex:number;eventType:string;payload:Record<string,unknown>}):Promise<AcademyProgressEvent>; updateEnrollment(id:string,userId:string,status:AcademyEnrollmentStatus,progressPercent:number,completedModules:number,refundEligible:boolean):Promise<AcademyEnrollment|null>; }
export class MemoryAcademyRepository implements AcademyRepository {
 private courses:AcademyCourse[]=[{id:'hlabi-property-professional-foundation',title:'Hlabi Property Professional Foundation',description:'A practical foundation for people preparing for a property career.',modules:['Property fundamentals','Buyer and seller journeys','Listing and marketing practice','Negotiation and client communication','Ethics, compliance and professional conduct','AI tools for property work'],active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}];
 private enrollments=new Map<string,AcademyEnrollment>(); private events:AcademyProgressEvent[]=[];
 async listCourses(){return this.courses.filter(c=>c.active)} async getCourse(id:string){return this.courses.find(c=>c.id===id&&c.active)??null}
 async enroll(input:{userId:string;courseId:string}){const old=[...this.enrollments.values()].find(e=>e.userId===input.userId&&e.courseId===input.courseId&&e.status!=='WITHDRAWN');if(old)return old;const now=new Date().toISOString();const e:AcademyEnrollment={id:randomUUID(),...input,status:'ENROLLED',progressPercent:0,completedModules:0,refundEligible:false,createdAt:now,updatedAt:now};this.enrollments.set(e.id,e);return e}
 async getEnrollment(id:string,userId:string){const e=this.enrollments.get(id);return e?.userId===userId?e:null} async listEnrollments(userId:string){return [...this.enrollments.values()].filter(e=>e.userId===userId)}
 async recordProgress(input:{enrollmentId:string;userId:string;moduleIndex:number;eventType:string;payload:Record<string,unknown>}){const e=await this.getEnrollment(input.enrollmentId,input.userId);if(!e)throw new Error('ENROLLMENT_NOT_FOUND');const c=await this.getCourse(e.courseId);if(!c)throw new Error('COURSE_NOT_FOUND');const completed=Math.max(e.completedModules,input.moduleIndex+1);const progress=Math.min(100,Math.round(completed/c.modules.length*100));const status=progress>=100?'COMPLETED':'IN_PROGRESS';const refundEligible=progress>=100;this.enrollments.set(e.id,{...e,status,progressPercent:progress,completedModules:completed,refundEligible,updatedAt:new Date().toISOString()});const event:AcademyProgressEvent={id:randomUUID(),...input,createdAt:new Date().toISOString()};this.events.push(event);return event}
 async updateEnrollment(id:string,userId:string,status:AcademyEnrollmentStatus,progressPercent:number,completedModules:number,refundEligible:boolean){const e=await this.getEnrollment(id,userId);if(!e)return null;const updated={...e,status,progressPercent,completedModules,refundEligible,updatedAt:new Date().toISOString()};this.enrollments.set(id,updated);return updated}
}
