import { ACADEMY_READINESS_EXAM_VERSION } from './academyReadinessExam.js';

export type ReadinessExamQuestion = {
  id:string; sectionId:'SECTION-A'|'SECTION-B'|'SECTION-C'; prompt:string; kind:'KNOWLEDGE'|'SIMULATION'; points:number; competencyIds:string[]; options?:string[]; correctAnswer?:string;
};

export const ACADEMY_READINESS_EXAM_QUESTIONS:ReadinessExamQuestion[]=[
 {id:'RDX-A01',sectionId:'SECTION-A',prompt:'Which principle best describes the professional duty when a material fact could affect a client decision?',kind:'KNOWLEDGE',points:5,competencyIds:['LEG-01','CON-01'],options:['Disclose or appropriately address the material fact before the client relies on the information.','Withhold it unless the client asks the exact question.','Mention it only after an offer is accepted.','Leave the decision entirely to the other party.'],correctAnswer:'Disclose or appropriately address the material fact before the client relies on the information.'},
 {id:'RDX-A02',sectionId:'SECTION-A',prompt:'A practitioner identifies a conflict of interest. What is the most defensible immediate response?',kind:'KNOWLEDGE',points:5,competencyIds:['ETH-01','FID-01'],options:['Ignore it if the transaction is commercially attractive.','Record, disclose and manage or escalate the conflict according to applicable requirements and instructions.','Ask a colleague to hide the conflict from the client.','Proceed first and document it only if challenged.'],correctAnswer:'Record, disclose and manage or escalate the conflict according to applicable requirements and instructions.'},
 {id:'RDX-A03',sectionId:'SECTION-A',prompt:'Why are traceable records important in regulated property practice?',kind:'KNOWLEDGE',points:5,competencyIds:['COM-01','ETH-01'],options:['They replace professional judgement.','They provide an auditable record of instructions, decisions, disclosures and actions.','They guarantee that a transaction will close.','They eliminate the need for client communication.'],correctAnswer:'They provide an auditable record of instructions, decisions, disclosures and actions.'},
 {id:'RDX-A04',sectionId:'SECTION-A',prompt:'When using AI to draft client-facing property information, what remains the practitioner’s responsibility?',kind:'KNOWLEDGE',points:5,competencyIds:['COM-01','JUD-01'],options:['Nothing, because the AI generated it.','Only the formatting.','Verification of material facts, protection of confidential information and accountable professional judgement.','Only the spelling.'],correctAnswer:'Verification of material facts, protection of confidential information and accountable professional judgement.'},
 {id:'RDX-A05',sectionId:'SECTION-A',prompt:'Explain how you would respond if a client instructs you to omit a material fact from marketing information.',kind:'SIMULATION',points:10,competencyIds:['LEG-01','ETH-01','CON-01','COM-01']},
 {id:'RDX-B01',sectionId:'SECTION-B',prompt:'A buyer has not established affordability but wants immediate viewings. What should happen before significant next steps?',kind:'KNOWLEDGE',points:5,competencyIds:['CON-01','APP-01'],options:['Proceed without clarification because viewings create momentum.','Clarify requirements, affordability and authority/consent, then document an appropriate next-step plan.','Tell the buyer to make an offer first.','Send the buyer’s personal information to every seller.'],correctAnswer:'Clarify requirements, affordability and authority/consent, then document an appropriate next-step plan.'},
 {id:'RDX-B02',sectionId:'SECTION-B',prompt:'During negotiation, two client instructions appear inconsistent. What is the strongest professional response?',kind:'KNOWLEDGE',points:5,competencyIds:['FID-01','JUD-01'],options:['Choose whichever instruction is more profitable.','Clarify the client’s current authorised instruction, preserve confidentiality and document the decision path.','Reveal confidential information to resolve the conflict.','Allow the other party to decide.'],correctAnswer:'Clarify the client’s current authorised instruction, preserve confidentiality and document the decision path.'},
 {id:'RDX-B03',sectionId:'SECTION-B',prompt:'Describe a traceable workflow for taking a property enquiry from initial requirements through a documented next action.',kind:'SIMULATION',points:15,competencyIds:['CON-01','APP-01','JUD-01']},
 {id:'RDX-B04',sectionId:'SECTION-B',prompt:'Describe the checks you would perform before relying on an AI-generated statement in a client communication.',kind:'SIMULATION',points:15,competencyIds:['COM-01','APP-01','JUD-01']},
 {id:'RDX-C01',sectionId:'SECTION-C',prompt:'Integrated case: A seller wants a fast sale, asks you to omit a known property issue from marketing, and asks an AI tool to produce a persuasive description. Explain your professional response from instruction-taking through documentation and escalation.',kind:'SIMULATION',points:20,competencyIds:['LEG-01','ETH-01','CON-01','COM-01','FID-01','APP-01','JUD-01']},
 {id:'RDX-C02',sectionId:'SECTION-C',prompt:'Integrated case: A buyer is financially uncertain, wants to submit an aggressive offer immediately, and provides sensitive personal information for an AI assistant. Set out the safe, client-centred sequence of actions and records you would create.',kind:'SIMULATION',points:20,competencyIds:['CON-01','COM-01','APP-01','JUD-01']}
];

export const READINESS_EXAM_MAX_SCORE=ACADEMY_READINESS_EXAM_QUESTIONS.reduce((sum,q)=>sum+q.points,0);
export const readinessExamQuestionBankVersion=ACADEMY_READINESS_EXAM_VERSION;
export const publicReadinessExamQuestion=(q:ReadinessExamQuestion)=>{const {correctAnswer,...safe}=q;return safe;};
