import { z } from 'zod';
import type { Express, RequestHandler } from 'express';
import { authenticatedPrincipal } from './authentication.js';
import type { AcademyRepository } from './academyRepository.js';
import type { AcademyAssessmentRepository } from './academyAssessmentRepository.js';

export function registerAcademyAssessmentRoutes(app:Express,authenticated:RequestHandler,academy:AcademyRepository,repo:AcademyAssessmentRepository){
 const submit=z.object({assessmentId:z.string().min(1),answers:z.record(z.string()).default({})});
 const review=z.object({score:z.number().min(0),status:z.enum(['PASSED','FAILED']),feedback:z.string().max(3000)});
 const reviewerOnly=(res:any)=>authenticatedPrincipal(res).role==='ACADEMY_REVIEWER'||authenticatedPrincipal(res).role==='ADMIN';
 app.get('/api/v1/academy/enrollments/:enrollmentId/assessments',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academy.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});const course=await academy.getCourse(e.courseId);if(!course)return res.status(404).json({error:'COURSE_NOT_FOUND'});const results=[];for(let i=0;i<course.modules.length;i++)results.push(...await repo.listAssessments(course.id,i));return res.json(results.map(({questions,...a})=>({...a,questions:questions.map(({correctAnswer,...q})=>q)})));});
 app.get('/api/v1/academy/enrollments/:enrollmentId/assessment-attempts',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academy.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});return res.json(await repo.listAttempts(e.id,p.userId));});
 app.post('/api/v1/academy/enrollments/:enrollmentId/assessment-attempts',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const e=await academy.getEnrollment(req.params.enrollmentId,p.userId);if(!e)return res.status(404).json({error:'ENROLLMENT_NOT_FOUND'});const v=submit.safeParse(req.body);if(!v.success)return res.status(400).json({error:'INVALID_ASSESSMENT_ATTEMPT',details:v.error.flatten()});const a=await repo.getAssessment(v.data.assessmentId);if(!a||a.courseId!==e.courseId)return res.status(404).json({error:'ASSESSMENT_NOT_FOUND'});const max=a.questions.reduce((n,q)=>n+q.points,0);const objective=a.questions.filter(q=>q.kind==='MULTIPLE_CHOICE');const objectiveMax=objective.reduce((n,q)=>n+q.points,0);const earned=objective.reduce((n,q)=>n+(v.data.answers[q.id]===q.correctAnswer?q.points:0),0);const score=a.kind==='KNOWLEDGE'&&objectiveMax>0?Math.round(earned/objectiveMax*100):null;const status=score===null?'NEEDS_REVIEW':score>=a.passingScore?'PASSED':'FAILED';const attempt=await repo.createAttempt({assessmentId:a.id,enrollmentId:e.id,userId:p.userId,answers:v.data.answers,score,maxScore:max,status});return res.status(201).json(attempt);});
 app.get('/api/v1/academy/assessment-attempts/:attemptId',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);const a=await repo.getAttempt(req.params.attemptId,p.userId);if(!a)return res.status(404).json({error:'ATTEMPT_NOT_FOUND'});return res.json(a);});
 app.get('/api/v1/academy/reviewer/queue',authenticated,async(req,res)=>{if(!reviewerOnly(res))return res.status(403).json({error:'REVIEWER_ROLE_REQUIRED'});return res.json(await repo.listReviewQueue());});
 app.get('/api/v1/academy/reviewer/attempts/:attemptId',authenticated,async(req,res)=>{if(!reviewerOnly(res))return res.status(403).json({error:'REVIEWER_ROLE_REQUIRED'});const a=await repo.getAttemptForReviewer(req.params.attemptId);if(!a)return res.status(404).json({error:'ATTEMPT_NOT_FOUND'});return res.json(a);});
 app.post('/api/v1/academy/reviewer/attempts/:attemptId/review',authenticated,async(req,res)=>{if(!reviewerOnly(res))return res.status(403).json({error:'REVIEWER_ROLE_REQUIRED'});const v=review.safeParse(req.body);if(!v.success)return res.status(400).json({error:'INVALID_REVIEW',details:v.error.flatten()});const p=authenticatedPrincipal(res);const a=await repo.getAttemptForReviewer(req.params.attemptId);if(!a)return res.status(404).json({error:'ATTEMPT_NOT_FOUND'});if(a.status!=='NEEDS_REVIEW')return res.status(409).json({error:'ATTEMPT_ALREADY_REVIEWED'});const reviewed=await repo.reviewAttempt(a.id,p.userId,v.data.score,v.data.status,v.data.feedback);if(!reviewed)return res.status(409).json({error:'ATTEMPT_REVIEW_CONFLICT'});return res.json(reviewed);});
}
