import type { Express } from 'express';
import { z } from 'zod';
import { authenticatedPrincipal } from './authentication.js';
import type { BillingRepository } from './billingRepository.js';
import type { PaymentProvider } from './billingDomain.js';
import type { HomeownerRepository } from './repository.js';

const subscriptionSchema=z.object({propertyId:z.string().min(1),planCode:z.string().min(2).max(80),amountMinor:z.number().int().positive(),currency:z.string().length(3).default('ZAR'),interval:z.enum(['MONTH','YEAR']),returnUrl:z.string().url().optional()});

export function registerBillingRoutes(app:Express,authenticated:any,billing:BillingRepository,homeowner:HomeownerRepository,paymentProvider:PaymentProvider){
 app.post('/api/v1/homeowner/subscriptions',authenticated,async(req,res)=>{const parsed=subscriptionSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_SUBSCRIPTION',details:parsed.error.flatten()});const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeowner.getPropertyForOwner(parsed.data.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const existing=await billing.getSubscriptionForOwner(property.id,p.userId);if(existing)return res.status(409).json({error:'SUBSCRIPTION_EXISTS',subscription:existing});const provider=paymentProvider.name;const reference=`HLABI-${crypto.randomUUID()}`;const result=await paymentProvider.createPayment({amountMinor:parsed.data.amountMinor,currency:parsed.data.currency,reference,customerId:p.userId,returnUrl:parsed.data.returnUrl});const transaction=await billing.createTransaction({ownerId:p.userId,propertyId:property.id,provider,reference,amountMinor:parsed.data.amountMinor,currency:parsed.data.currency,status:result.status,providerTransactionRef:result.externalId,idempotencyKey:reference});const subscription=await billing.createSubscription({ownerId:p.userId,propertyId:property.id,planCode:parsed.data.planCode,status:result.status==='FAILED'?'PAST_DUE':'PENDING',currency:parsed.data.currency,amountMinor:parsed.data.amountMinor,interval:parsed.data.interval,provider});return res.status(201).json({subscription,transaction});});
 app.get('/api/v1/homeowner/properties/:propertyId/subscription',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeowner.getPropertyForOwner(req.params.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const subscription=await billing.getSubscriptionForOwner(property.id,p.userId);if(!subscription)return res.status(404).json({error:'SUBSCRIPTION_NOT_FOUND'});return res.json(subscription);});
 app.get('/api/v1/homeowner/properties/:propertyId/payments',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeowner.getPropertyForOwner(req.params.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});return res.json(await billing.listTransactionsForOwner(p.userId,property.id));});
}
