import { z } from 'zod';
import type { Express, RequestHandler } from 'express';
import type { FranchiseAcceleratorRepository } from './franchiseAcceleratorRepository.js';
import { acceleratorStages, acceleratorStatuses, defaultAcceleratorChecklist, nextAcceleratorStage } from './franchiseAcceleratorDomain.js';
import type { AcademyRepository } from './academyRepository.js';
import type { AcademyAssessmentRepository } from './academyAssessmentRepository.js';
import type { AcademyReadinessExamRepository } from './academyReadinessExamRepository.js';

const updateSchema=z.object({stage:z.enum(acceleratorStages).optional(),status:z.enum(acceleratorStatuses).optional(),checklist:z.record(z.boolean()).optional(),territory:z.string().min(2).max(160).optional(),officeName:z.string().min(2).max(160).optional(),franchiseOpportunityId:z.string().min(1).max(160).optional(),notes:z.string().max(2000).optional()});

export function registerFranchiseAcceleratorRoutes(app:Express,authenticated:RequestHandler,repo:FranchiseAcceleratorRepository,academy:AcademyRepository,assessments:AcademyAssessmentRepository,readiness:AcademyReadinessExamRepository){
  app.get('/api/v1/academy/franchise-accelerator',authenticated,async(_req,res)=>{const p=res.locals.principal;if(!p)return res.status(401).json({error:'AUTH_REQUIRED'});let profile=await repo.get(p.userId);if(!profile)profile=await repo.create(p.userId);const enrollments=await academy.listEnrollments(p.userId);const enrollment=enrollments[0];let foundationComplete=false,evidencePackageReady=false,readinessPassed=false;if(enrollment){foundationComplete=enrollment.completedModules>=6;const attempts=await assessments.list(enrollment.id);const readinessAttempts=await readiness.list(enrollment.id);readinessPassed=readinessAttempts.some(x=>x.status==='PASSED');evidencePackageReady=foundationComplete&&attempts.every(x=>x.status==='PASSED'||x.status==='FAILED')&&readinessPassed;}
    const next=nextAcceleratorStage(profile.stage);return res.json({profile,readiness:{foundationComplete,evidencePackageReady,readinessPassed},stageRequirements:defaultAcceleratorChecklist,nextStage:next,statutoryBoundary:'Academy and accelerator evidence do not confer statutory registration, qualification, designation, or regulatory approval.'});});
  app.patch('/api/v1/academy/franchise-accelerator',authenticated,async(req,res)=>{const p=res.locals.principal;if(!p)return res.status(401).json({error:'AUTH_REQUIRED'});const parsed=updateSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_ACCELERATOR_UPDATE',details:parsed.error.flatten()});let profile=await repo.get(p.userId);if(!profile)profile=await repo.create(p.userId);if(parsed.data.stage&&acceleratorStages.indexOf(parsed.data.stage)<acceleratorStages.indexOf(profile.stage))return res.status(409).json({error:'STAGE_REGRESSION_NOT_ALLOWED'});if(parsed.data.status==='APPROVED'&&profile.stage!=='FRANCHISE')return res.status(409).json({error:'FRANCHISE_APPROVAL_REQUIRES_FRANCHISE_STAGE'});profile=await repo.update(p.userId,parsed.data);return res.json(profile);});
  app.post('/api/v1/academy/franchise-accelerator/advance',authenticated,async(_req,res)=>{const p=res.locals.principal;if(!p)return res.status(401).json({error:'AUTH_REQUIRED'});let profile=await repo.get(p.userId);if(!profile)profile=await repo.create(p.userId);const enrollments=await academy.listEnrollments(p.userId);const enrollment=enrollments[0];if(!enrollment||enrollment.completedModules<6)return res.status(409).json({error:'ACADEMY_FOUNDATION_REQUIRED'});if(profile.stage==='ACADEMY'){const attempts=await readiness.list(enrollment.id);if(!attempts.some(x=>x.status==='PASSED'))return res.status(409).json({error:'READINESS_EXAM_REQUIRED'});profile=await repo.update(p.userId,{stage:'AGENT',status:'READY',checklist:{...profile.checklist,foundationComplete:true,evidencePackageReady:true}});return res.json(profile);}if(profile.stage==='AGENT'){const required=defaultAcceleratorChecklist.OFFICE;const complete=required.every(k=>profile.checklist[k]===true);if(!complete)return res.status(409).json({error:'OFFICE_READINESS_INCOMPLETE',required});profile=await repo.update(p.userId,{stage:'OFFICE',status:'READY'});return res.json(profile);}if(profile.stage==='OFFICE'){const required=defaultAcceleratorChecklist.FRANCHISE;const complete=required.every(k=>profile.checklist[k]===true);if(!complete)return res.status(409).json({error:'FRANCHISE_READINESS_INCOMPLETE',required});profile=await repo.update(p.userId,{stage:'FRANCHISE',status:'IN_PROGRESS'});return res.json(profile);}return res.json(profile);});
}
