import type { Express, RequestHandler } from 'express';
import { z } from 'zod';
import { authenticatedPrincipal } from './authentication.js';
import type { HomeownerRepository } from './repository.js';
import type { JourneyRepository } from './journeyRepository.js';

const buyer=z.object({preferredSuburb:z.string().max(120).optional(),city:z.string().max(120).optional(),province:z.string().max(120).optional(),propertyTypes:z.array(z.string().max(40)).max(10).default([]),minBudgetCents:z.number().int().nonnegative().optional(),maxBudgetCents:z.number().int().nonnegative().optional(),bedrooms:z.number().int().min(0).max(20).optional(),financingStatus:z.enum(['CASH','PRE_APPROVED','NEEDS_FINANCE','UNKNOWN']).default('UNKNOWN')});
const seller=z.object({propertyId:z.string().min(1),targetSaleDate:z.string().datetime().optional(),reason:z.string().max(500).optional(),readiness:z.enum(['NOT_STARTED','PREPARING','READY_TO_LIST']).default('NOT_STARTED'),notes:z.string().max(3000).optional()});
const investor=z.object({targetArea:z.string().max(200).optional(),strategy:z.enum(['LONG_TERM_RENTAL','FLIP','DEVELOPMENT','MIXED']),minBudgetCents:z.number().int().nonnegative().optional(),maxBudgetCents:z.number().int().nonnegative().optional(),targetYieldPercent:z.number().min(0).max(100).optional(),riskProfile:z.enum(['CONSERVATIVE','BALANCED','GROWTH'])});
export function registerJourneyRoutes(app:Express,authenticated:RequestHandler,repository:JourneyRepository,homeownerRepository:HomeownerRepository){
 app.post('/api/v1/buyer/journey',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='BUYER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const parsed=buyer.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_BUYER_JOURNEY',details:parsed.error.flatten()});return res.status(200).json(await repository.upsertBuyer({userId:p.userId,...parsed.data}));});
 app.get('/api/v1/buyer/journey',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='BUYER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const journey=await repository.getBuyer(p.userId);return journey?res.json(journey):res.status(404).json({error:'BUYER_JOURNEY_NOT_FOUND'});});
 app.post('/api/v1/seller/journey',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const parsed=seller.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_SELLER_JOURNEY',details:parsed.error.flatten()});const property=await homeownerRepository.getPropertyForOwner(parsed.data.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});return res.status(200).json(await repository.upsertSeller({userId:p.userId,propertyId:property.id,targetSaleDate:parsed.data.targetSaleDate,reason:parsed.data.reason,readiness:parsed.data.readiness,notes:parsed.data.notes}));});
 app.get('/api/v1/seller/journey/:propertyId',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeownerRepository.getPropertyForOwner(req.params.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const journey=await repository.getSeller(property.id,p.userId);return journey?res.json(journey):res.status(404).json({error:'SELLER_JOURNEY_NOT_FOUND'});});
 app.post('/api/v1/investor/journey',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='INVESTOR')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const parsed=investor.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_INVESTOR_JOURNEY',details:parsed.error.flatten()});return res.status(200).json(await repository.upsertInvestor({userId:p.userId,...parsed.data}));});
 app.get('/api/v1/investor/journey',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='INVESTOR')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const journey=await repository.getInvestor(p.userId);return journey?res.json(journey):res.status(404).json({error:'INVESTOR_JOURNEY_NOT_FOUND'});});
}
