import type {Express,RequestHandler} from 'express';
import {z} from 'zod';
import {authenticatedPrincipal} from './authentication.js';
import type {HomeownerRepository} from './repository.js';
import type {ListingRepository} from './listingRepository.js';

const patch=z.object({title:z.string().min(5).max(160).optional(),description:z.string().min(20).max(5000).optional(),askingPriceCents:z.number().int().positive().optional(),bedrooms:z.number().int().min(0).max(30).optional(),bathrooms:z.number().min(0).max(30).optional(),features:z.array(z.string().max(100)).max(30).optional()});
export function registerListingRoutes(app:Express,auth:RequestHandler,repo:ListingRepository,properties:HomeownerRepository){
 app.get('/api/v1/seller/properties/:propertyId/listing',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});if(!await properties.getPropertyForOwner(req.params.propertyId,p.userId))return res.status(404).json({error:'PROPERTY_NOT_FOUND'});return res.json(await repo.getForSeller(req.params.propertyId,p.userId));});
 app.post('/api/v1/seller/properties/:propertyId/listing',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});if(!await properties.getPropertyForOwner(req.params.propertyId,p.userId))return res.status(404).json({error:'PROPERTY_NOT_FOUND'});if(await repo.getForSeller(req.params.propertyId,p.userId))return res.status(409).json({error:'LISTING_ALREADY_EXISTS'});const parsed=patch.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_LISTING',details:parsed.error.flatten()});return res.status(201).json(await repo.create({propertyId:req.params.propertyId,sellerId:p.userId,status:'DRAFT',title:parsed.data.title??'Property listing draft',description:parsed.data.description??'',askingPriceCents:parsed.data.askingPriceCents,bedrooms:parsed.data.bedrooms,bathrooms:parsed.data.bathrooms,features:parsed.data.features??[]}));});
 app.patch('/api/v1/seller/properties/:propertyId/listing',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});if(!await properties.getPropertyForOwner(req.params.propertyId,p.userId))return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const parsed=patch.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_LISTING',details:parsed.error.flatten()});const listing=await repo.updateForSeller(req.params.propertyId,p.userId,parsed.data);return listing?res.json(listing):res.status(404).json({error:'LISTING_NOT_FOUND'});});
 app.post('/api/v1/seller/properties/:propertyId/listing/publish',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});if(!await properties.getPropertyForOwner(req.params.propertyId,p.userId))return res.status(404).json({error:'PROPERTY_NOT_FOUND'});if(req.body?.confirm!==true)return res.status(400).json({error:'CONFIRMATION_REQUIRED'});const listing=await repo.getForSeller(req.params.propertyId,p.userId);if(!listing)return res.status(404).json({error:'LISTING_NOT_FOUND'});if(!listing.title||listing.description.length<20||!listing.askingPriceCents)return res.status(409).json({error:'LISTING_INCOMPLETE'});if(listing.status!=='READY_TO_LIST'&&listing.status!=='DRAFT')return res.status(409).json({error:'LISTING_NOT_PUBLISHABLE'});const updated=await repo.updateForSeller(req.params.propertyId,p.userId,{status:'LISTED'});return res.status(200).json(updated);});
 app.get('/api/v1/properties/listings',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(!['BUYER','INVESTOR'].includes(p.role))return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const area=typeof req.query.area==='string'?req.query.area:undefined;const max=typeof req.query.maxPriceCents==='string'?Number(req.query.maxPriceCents):undefined;const propertyType=typeof req.query.propertyType==='string'?req.query.propertyType:undefined;return res.json(await repo.listPublic({area,maxPriceCents:Number.isFinite(max)?max:undefined,propertyType}));});
}
