import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { AgentRepository } from './agentRepository.js';
import type { AgentStaffMember, AgentStatus, AgentTask, AgentTaskEvent, AgentTaskStatus } from './agentDomain.js';

const mapStaff = (r: any): AgentStaffMember => ({ id:r.id, ownerId:r.owner_id, role:r.role, name:r.name, description:r.description ?? undefined, status:r.status, configuration:r.configuration ?? {}, createdAt:r.created_at.toISOString(), updatedAt:r.updated_at.toISOString() });
const mapTask = (r: any): AgentTask => ({ id:r.id, agentId:r.agent_id, ownerId:r.owner_id, propertyId:r.property_id ?? undefined, type:r.type, input:r.input ?? {}, status:r.status, output:r.output ?? undefined, requiresApproval:r.requires_approval, idempotencyKey:r.idempotency_key ?? undefined, errorCode:r.error_code ?? undefined, createdAt:r.created_at.toISOString(), startedAt:r.started_at?.toISOString(), completedAt:r.completed_at?.toISOString() });
const mapEvent = (r: any): AgentTaskEvent => ({ id:r.id, taskId:r.task_id, ownerId:r.owner_id, eventType:r.event_type, payload:r.payload ?? {}, createdAt:r.created_at.toISOString() });

export class PostgresAgentRepository implements AgentRepository {
  constructor(private readonly pool: Pool) {}
  async listStaff(ownerId:string){ const {rows}=await this.pool.query('SELECT * FROM agent_staff WHERE owner_id=$1 ORDER BY created_at DESC',[ownerId]); return rows.map(mapStaff); }
  async getStaffForOwner(agentId:string,ownerId:string){ const {rows}=await this.pool.query('SELECT * FROM agent_staff WHERE id=$1 AND owner_id=$2',[agentId,ownerId]); return rows[0]?mapStaff(rows[0]):null; }
  async createStaff(input:Omit<AgentStaffMember,'id'|'createdAt'|'updatedAt'>){ const id=randomUUID(); const {rows}=await this.pool.query(`INSERT INTO agent_staff (id,owner_id,role,name,description,status,configuration) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[id,input.ownerId,input.role,input.name,input.description??null,input.status,input.configuration]); return mapStaff(rows[0]); }
  async updateStaffStatus(agentId:string,ownerId:string,status:AgentStatus){ const {rows}=await this.pool.query('UPDATE agent_staff SET status=$1,updated_at=NOW() WHERE id=$2 AND owner_id=$3 RETURNING *',[status,agentId,ownerId]); return rows[0]?mapStaff(rows[0]):null; }
  async createTask(input:Omit<AgentTask,'id'|'createdAt'|'status'>&{status?:AgentTaskStatus}){ const id=randomUUID(); const {rows}=await this.pool.query(`INSERT INTO agent_tasks (id,agent_id,owner_id,property_id,type,input,status,requires_approval,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,input.agentId,input.ownerId,input.propertyId??null,input.type,input.input,input.status??'QUEUED',input.requiresApproval,input.idempotencyKey??null]); return mapTask(rows[0]); }
  async getTaskForOwner(taskId:string,ownerId:string){ const {rows}=await this.pool.query('SELECT * FROM agent_tasks WHERE id=$1 AND owner_id=$2',[taskId,ownerId]); return rows[0]?mapTask(rows[0]):null; }
  async listTasks(ownerId:string,agentId?:string){ const {rows}=await this.pool.query('SELECT * FROM agent_tasks WHERE owner_id=$1 AND ($2::text IS NULL OR agent_id=$2) ORDER BY created_at DESC',[ownerId,agentId??null]); return rows.map(mapTask); }
  async updateTask(taskId:string,ownerId:string,patch:Partial<Pick<AgentTask,'status'|'output'|'errorCode'|'startedAt'|'completedAt'>>){ const fields:string[]=[];const values:any[]=[];let i=1;for(const [key,value] of Object.entries(patch)){const col={status:'status',output:'output',errorCode:'error_code',startedAt:'started_at',completedAt:'completed_at'}[key];if(col){fields.push(`${col}=$${i++}`);values.push(value??null);}}if(!fields.length)return this.getTaskForOwner(taskId,ownerId);values.push(taskId,ownerId);const {rows}=await this.pool.query(`UPDATE agent_tasks SET ${fields.join(',')} WHERE id=$${i++} AND owner_id=$${i} RETURNING *`,values);return rows[0]?mapTask(rows[0]):null; }
  async appendEvent(input:Omit<AgentTaskEvent,'id'|'createdAt'>){ const id=randomUUID();const {rows}=await this.pool.query('INSERT INTO agent_task_events (id,task_id,owner_id,event_type,payload) VALUES ($1,$2,$3,$4,$5) RETURNING *',[id,input.taskId,input.ownerId,input.eventType,input.payload]);return mapEvent(rows[0]); }
  async hasApprovalGrant(taskId:string,ownerId:string){ const {rows}=await this.pool.query("SELECT 1 FROM agent_task_events WHERE task_id=$1 AND owner_id=$2 AND event_type='HUMAN_APPROVAL_GRANTED' LIMIT 1",[taskId,ownerId]); return Boolean(rows[0]); }
}
