import type { Pool } from 'pg';
import type { AcademyCourse, AcademyEnrollment, AcademyEnrollmentStatus, AcademyProgressEvent } from './academyDomain.js';
import type { AcademyRepository } from './academyRepository.js';
const course=(r:any):AcademyCourse=>({id:r.id,title:r.title,description:r.description,modules:r.modules,active:r.active,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const enrollment=(r:any):AcademyEnrollment=>({id:r.id,userId:r.user_id,courseId:r.course_id,status:r.status,progressPercent:r.progress_percent,completedModules:r.completed_modules,refundEligible:r.refund_eligible,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
export class PostgresAcademyRepository implements AcademyRepository {
 constructor(private readonly pool:Pool){}
 async listCourses(){const {rows}=await this.pool.query('SELECT * FROM academy_courses WHERE active=true ORDER BY title');return rows.map(course);}
 async getCourse(id:string){const {rows}=await this.pool.query('SELECT * FROM academy_courses WHERE id=$1 AND active=true',[id]);return rows[0]?course(rows[0]):null;}
 async enroll(input:{userId:string;courseId:string}){const {rows}=await this.pool.query(`INSERT INTO academy_enrollments(user_id,course_id) VALUES($1,$2) ON CONFLICT(user_id,course_id) DO UPDATE SET updated_at=NOW() RETURNING *`,[input.userId,input.courseId]);return enrollment(rows[0]);}
 async getEnrollment(id:string,userId:string){const {rows}=await this.pool.query('SELECT * FROM academy_enrollments WHERE id=$1 AND user_id=$2',[id,userId]);return rows[0]?enrollment(rows[0]):null;}
 async listEnrollments(userId:string){const {rows}=await this.pool.query('SELECT * FROM academy_enrollments WHERE user_id=$1 ORDER BY updated_at DESC',[userId]);return rows.map(enrollment);}
 async recordProgress(input:{enrollmentId:string;userId:string;moduleIndex:number;eventType:string;payload:Record<string,unknown>}){const e=await this.getEnrollment(input.enrollmentId,input.userId);if(!e)throw new Error('ENROLLMENT_NOT_FOUND');const c=await this.getCourse(e.courseId);if(!c)throw new Error('COURSE_NOT_FOUND');const completed=Math.max(e.completedModules,input.moduleIndex+1);const progress=Math.min(100,Math.round(completed/c.modules.length*100));await this.updateEnrollment(e.id,e.userId,progress>=100?'COMPLETED':'IN_PROGRESS',progress,completed,progress>=100);const {rows}=await this.pool.query('INSERT INTO academy_progress_events(enrollment_id,user_id,module_index,event_type,payload) VALUES($1,$2,$3,$4,$5) RETURNING *',[input.enrollmentId,input.userId,input.moduleIndex,input.eventType,input.payload]);const r=rows[0];return {id:r.id,enrollmentId:r.enrollment_id,userId:r.user_id,moduleIndex:r.module_index,eventType:r.event_type,payload:r.payload??{},createdAt:r.created_at.toISOString()};}
 async updateEnrollment(id:string,userId:string,status:AcademyEnrollmentStatus,progressPercent:number,completedModules:number,refundEligible:boolean){const {rows}=await this.pool.query('UPDATE academy_enrollments SET status=$3,progress_percent=$4,completed_modules=$5,refund_eligible=$6,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *',[id,userId,status,progressPercent,completedModules,refundEligible]);return rows[0]?enrollment(rows[0]):null;}
}
