import type { Pool } from 'pg';
import type { AcademyAssessment, AcademyAssessmentAttempt, AcademyAttemptStatus } from './academyAssessmentDomain.js';
import type { AcademyAssessmentRepository } from './academyAssessmentRepository.js';
import { randomUUID } from 'node:crypto';

const assessmentData=():AcademyAssessment[]=[
 {id:'module-0-knowledge',courseId:'hlabi-property-professional-foundation',moduleIndex:0,title:'Property Fundamentals Check',kind:'KNOWLEDGE',passingScore:70,questions:[{id:'q1',prompt:'Which party is the buyer in a property transaction?',options:['Person acquiring the property','Person listing the property'],correctAnswer:'Person acquiring the property',points:10,kind:'MULTIPLE_CHOICE'},{id:'q2',prompt:'Which record should be kept for a client interaction?',options:['A contemporaneous client record','Nothing unless a dispute occurs'],correctAnswer:'A contemporaneous client record',points:10,kind:'MULTIPLE_CHOICE'}]},
 {id:'module-1-simulation',courseId:'hlabi-property-professional-foundation',moduleIndex:1,title:'Buyer Journey Simulation',kind:'SIMULATION',passingScore:70,questions:[{id:'scenario',prompt:'A buyer has preferences, a budget and a preferred area. Describe the first three actions you would take and what you would document.',points:30,kind:'SHORT_RESPONSE'}],rubric:['Clarifies requirements and affordability','Documents buyer preferences and consent','Creates a traceable next-step plan']},
 {id:'module-2-knowledge',courseId:'hlabi-property-professional-foundation',moduleIndex:2,title:'Listing, Marketing and Compliance Check',kind:'KNOWLEDGE',passingScore:70,questions:[{id:'q1',prompt:'Before publishing property marketing, what should a practitioner verify?',options:['That material information and required disclosures are accurate','Only that the listing looks attractive'],correctAnswer:'That material information and required disclosures are accurate',points:10,kind:'MULTIPLE_CHOICE'},{id:'q2',prompt:'What is the safer response when a client asks you to omit a material fact?',options:['Explain the disclosure/compliance obligation and escalate when required','Agree if the client promises not to mention it'],correctAnswer:'Explain the disclosure/compliance obligation and escalate when required',points:10,kind:'MULTIPLE_CHOICE'}]},
 {id:'module-3-simulation',courseId:'hlabi-property-professional-foundation',moduleIndex:3,title:'Negotiation and Professional Judgement Simulation',kind:'SIMULATION',passingScore:70,questions:[{id:'scenario',prompt:'Two parties have conflicting priorities in a negotiation. Explain how you would clarify instructions, identify risks, protect confidential information and document the agreed next steps.',points:40,kind:'SHORT_RESPONSE'}],rubric:['Clarifies authority and client instructions','Identifies and manages conflicts or risks','Protects confidential information','Documents an auditable next-step plan']},
 {id:'module-4-knowledge',courseId:'hlabi-property-professional-foundation',moduleIndex:4,title:'Ethics, Fiduciary Duties and Regulatory Compliance Check',kind:'KNOWLEDGE',passingScore:70,questions:[{id:'q1',prompt:'When a practitioner identifies a conflict of interest, what should happen first?',options:['Identify, disclose and manage the conflict according to applicable obligations','Ignore it unless a complaint is made'],correctAnswer:'Identify, disclose and manage the conflict according to applicable obligations',points:10,kind:'MULTIPLE_CHOICE'},{id:'q2',prompt:'Which approach best reflects professional conduct?',options:['Keep traceable records, act within authority and escalate uncertainty','Rely on memory when the transaction is straightforward'],correctAnswer:'Keep traceable records, act within authority and escalate uncertainty',points:10,kind:'MULTIPLE_CHOICE'}]},
 {id:'module-5-simulation',courseId:'hlabi-property-professional-foundation',moduleIndex:5,title:'AI-Assisted Property Practice Simulation',kind:'SIMULATION',passingScore:70,questions:[{id:'scenario',prompt:'You use an AI tool to help prepare client-facing property work. Describe how you would verify outputs, protect confidential information, identify unsupported claims and retain human accountability for the final work.',points:40,kind:'SHORT_RESPONSE'}],rubric:['Verifies AI-generated information against authoritative sources','Protects confidential and personal information','Separates facts from assumptions or unsupported claims','Retains human accountability and an auditable review trail']}
];
const map=(r:any):AcademyAssessmentAttempt=>({id:r.id,assessmentId:r.assessment_id,enrollmentId:r.enrollment_id,userId:r.user_id,answers:r.answers??{},score:r.score,maxScore:r.max_score,status:r.status,reviewerId:r.reviewer_id??undefined,feedback:r.feedback??undefined,submittedAt:r.submitted_at.toISOString(),reviewedAt:r.reviewed_at?.toISOString()});
export class PostgresAcademyAssessmentRepository implements AcademyAssessmentRepository{constructor(private readonly pool:Pool){} async listAssessments(courseId:string,moduleIndex:number){return assessmentData().filter(a=>a.courseId===courseId&&a.moduleIndex===moduleIndex)} async getAssessment(id:string){return assessmentData().find(a=>a.id===id)??null} async createAttempt(input:{assessmentId:string;enrollmentId:string;userId:string;answers:Record<string,string>;score:number|null;maxScore:number;status:AcademyAttemptStatus}){const id=randomUUID();const{rows}=await this.pool.query('INSERT INTO academy_assessment_attempts(id,assessment_id,enrollment_id,user_id,answers,score,max_score,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id,input.assessmentId,input.enrollmentId,input.userId,input.answers,input.score,input.maxScore,input.status]);return map(rows[0])} async getAttempt(id:string,userId:string){const{rows}=await this.pool.query('SELECT * FROM academy_assessment_attempts WHERE id=$1 AND user_id=$2',[id,userId]);return rows[0]?map(rows[0]):null} async getAttemptForReviewer(id:string){const{rows}=await this.pool.query('SELECT * FROM academy_assessment_attempts WHERE id=$1',[id]);return rows[0]?map(rows[0]):null} async listAttempts(enrollmentId:string,userId:string){const{rows}=await this.pool.query('SELECT * FROM academy_assessment_attempts WHERE enrollment_id=$1 AND user_id=$2 ORDER BY submitted_at DESC',[enrollmentId,userId]);return rows.map(map)} async listReviewQueue(){const{rows}=await this.pool.query("SELECT * FROM academy_assessment_attempts WHERE status='NEEDS_REVIEW' ORDER BY submitted_at ASC");return rows.map(map)} async reviewAttempt(id:string,reviewerId:string,score:number,status:AcademyAttemptStatus,feedback:string){const{rows}=await this.pool.query("UPDATE academy_assessment_attempts SET reviewer_id=$2,score=$3,status=$4,feedback=$5,reviewed_at=NOW() WHERE id=$1 AND status='NEEDS_REVIEW' RETURNING *",[id,reviewerId,score,status,feedback]);return rows[0]?map(rows[0]):null}}
