import type { Pool } from 'pg';
import type { JourneyRepository } from './journeyRepository.js';
import type { BuyerJourney, InvestorJourney, SellerJourney } from './journeyDomain.js';

const buyer=(r:any):BuyerJourney=>({id:r.id,userId:r.user_id,preferredSuburb:r.preferred_suburb??undefined,city:r.city??undefined,province:r.province??undefined,propertyTypes:r.property_types??[],minBudgetCents:r.min_budget_cents??undefined,maxBudgetCents:r.max_budget_cents??undefined,bedrooms:r.bedrooms??undefined,financingStatus:r.financing_status??undefined,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const seller=(r:any):SellerJourney=>({id:r.id,userId:r.user_id,propertyId:r.property_id,targetSaleDate:r.target_sale_date?.toISOString(),reason:r.reason??undefined,readiness:r.readiness,notes:r.notes??undefined,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const investor=(r:any):InvestorJourney=>({id:r.id,userId:r.user_id,targetArea:r.target_area??undefined,strategy:r.strategy,minBudgetCents:r.min_budget_cents??undefined,maxBudgetCents:r.max_budget_cents??undefined,targetYieldPercent:r.target_yield_percent??undefined,riskProfile:r.risk_profile,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
export class PostgresJourneyRepository implements JourneyRepository {
  constructor(private readonly pool:Pool){}
  async upsertBuyer(input:Omit<BuyerJourney,'id'|'createdAt'|'updatedAt'>){const {rows}=await this.pool.query(`INSERT INTO buyer_journeys(user_id,preferred_suburb,city,province,property_types,min_budget_cents,max_budget_cents,bedrooms,financing_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(user_id) DO UPDATE SET preferred_suburb=EXCLUDED.preferred_suburb,city=EXCLUDED.city,province=EXCLUDED.province,property_types=EXCLUDED.property_types,min_budget_cents=EXCLUDED.min_budget_cents,max_budget_cents=EXCLUDED.max_budget_cents,bedrooms=EXCLUDED.bedrooms,financing_status=EXCLUDED.financing_status,updated_at=NOW() RETURNING *`,[input.userId,input.preferredSuburb??null,input.city??null,input.province??null,input.propertyTypes,input.minBudgetCents??null,input.maxBudgetCents??null,input.bedrooms??null,input.financingStatus??'UNKNOWN']);return buyer(rows[0]);}
  async getBuyer(userId:string){const {rows}=await this.pool.query('SELECT * FROM buyer_journeys WHERE user_id=$1',[userId]);return rows[0]?buyer(rows[0]):null;}
  async upsertSeller(input:Omit<SellerJourney,'id'|'createdAt'|'updatedAt'>){const {rows}=await this.pool.query(`INSERT INTO seller_journeys(user_id,property_id,target_sale_date,reason,readiness,notes) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,property_id) DO UPDATE SET target_sale_date=EXCLUDED.target_sale_date,reason=EXCLUDED.reason,readiness=EXCLUDED.readiness,notes=EXCLUDED.notes,updated_at=NOW() RETURNING *`,[input.userId,input.propertyId,input.targetSaleDate??null,input.reason??null,input.readiness,input.notes??null]);return seller(rows[0]);}
  async getSeller(propertyId:string,userId:string){const {rows}=await this.pool.query('SELECT * FROM seller_journeys WHERE property_id=$1 AND user_id=$2',[propertyId,userId]);return rows[0]?seller(rows[0]):null;}
  async upsertInvestor(input:Omit<InvestorJourney,'id'|'createdAt'|'updatedAt'>){const {rows}=await this.pool.query(`INSERT INTO investor_journeys(user_id,target_area,strategy,min_budget_cents,max_budget_cents,target_yield_percent,risk_profile) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET target_area=EXCLUDED.target_area,strategy=EXCLUDED.strategy,min_budget_cents=EXCLUDED.min_budget_cents,max_budget_cents=EXCLUDED.max_budget_cents,target_yield_percent=EXCLUDED.target_yield_percent,risk_profile=EXCLUDED.risk_profile,updated_at=NOW() RETURNING *`,[input.userId,input.targetArea??null,input.strategy,input.minBudgetCents??null,input.maxBudgetCents??null,input.targetYieldPercent??null,input.riskProfile]);return investor(rows[0]);}
  async getInvestor(userId:string){const {rows}=await this.pool.query('SELECT * FROM investor_journeys WHERE user_id=$1',[userId]);return rows[0]?investor(rows[0]):null;}
}
