import type { Express } from 'express';
import { z } from 'zod';
import type { RenewalRepository } from './renewalRepository.js';
import type { HomeownerRepository } from './repository.js';
import { authenticatedPrincipal } from './authentication.js';

const planSchema=z.object({propertyId:z.string().min(1),sourceAuditId:z.string().min(1).optional(),homeHealthAtStart:z.number().int().min(0).max(100).optional(),startDate:z.string().datetime().optional()});
const taskSchema=z.object({title:z.string().min(3).max(200),category:z.string().min(2).max(100),priority:z.enum(['LOW','MEDIUM','URGENT']),dueDate:z.string().datetime().optional()});
const taskStatusSchema=z.object({status:z.enum(['PLANNED','QUOTING','SCHEDULED','IN_PROGRESS','COMPLETED','SKIPPED']),serviceJobId:z.string().min(1).optional()});
const fiveYears=(date:string)=>{const d=new Date(date);d.setUTCFullYear(d.getUTCFullYear()+5);return d.toISOString();};

export function registerRenewalRoutes(app:Express,authenticated:any,repository:RenewalRepository,homeownerRepository:HomeownerRepository){
 app.post('/api/v1/homeowner/renewal-plans',authenticated,async(req,res)=>{const parsed=planSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_RENEWAL_PLAN',details:parsed.error.flatten()});const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeownerRepository.getPropertyForOwner(parsed.data.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const existing=await repository.getPlanForOwner(property.id,p.userId);if(existing)return res.status(409).json({error:'RENEWAL_PLAN_EXISTS',plan:existing});const start=parsed.data.startDate??new Date().toISOString();return res.status(201).json(await repository.createPlan({propertyId:property.id,ownerId:p.userId,status:'ACTIVE',cycleYears:5,startDate:start,nextReviewDate:fiveYears(start),homeHealthAtStart:parsed.data.homeHealthAtStart,sourceAuditId:parsed.data.sourceAuditId}));});
 app.get('/api/v1/homeowner/properties/:propertyId/renewal-plan',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const property=await homeownerRepository.getPropertyForOwner(req.params.propertyId,p.userId);if(!property)return res.status(404).json({error:'PROPERTY_NOT_FOUND'});const plan=await repository.getPlanForOwner(property.id,p.userId);if(!plan)return res.status(404).json({error:'RENEWAL_PLAN_NOT_FOUND'});return res.json(plan);});
 app.get('/api/v1/homeowner/renewal-plans/:planId/tasks',authenticated,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const plan=await repository.getPlanByIdForOwner(req.params.planId,p.userId);if(!plan)return res.status(404).json({error:'RENEWAL_PLAN_NOT_FOUND'});return res.json(await repository.listTasksForOwner(plan.id,p.userId));});
 app.post('/api/v1/homeowner/renewal-plans/:planId/tasks',authenticated,async(req,res)=>{const parsed=taskSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_RENEWAL_TASK',details:parsed.error.flatten()});const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const plan=await repository.getPlanByIdForOwner(req.params.planId,p.userId);if(!plan)return res.status(404).json({error:'RENEWAL_PLAN_NOT_FOUND'});return res.status(201).json(await repository.createTask({planId:plan.id,propertyId:plan.propertyId,ownerId:p.userId,title:parsed.data.title,category:parsed.data.category,priority:parsed.data.priority,status:'PLANNED',dueDate:parsed.data.dueDate}));});
 app.patch('/api/v1/homeowner/renewal-tasks/:taskId/status',authenticated,async(req,res)=>{const parsed=taskStatusSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_RENEWAL_TASK_STATUS',details:parsed.error.flatten()});const p=authenticatedPrincipal(res);if(p.role!=='HOMEOWNER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const task=await repository.updateTaskStatus(req.params.taskId,p.userId,parsed.data.status,parsed.data.serviceJobId);if(!task)return res.status(404).json({error:'RENEWAL_TASK_NOT_FOUND'});return res.json(task);});
}
