import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { SupplierEcosystemProfile, SupplierOnboardingStatus } from './supplierEcosystemDomain.js';

export interface SupplierEcosystemRepository {
  get(supplierId: string): Promise<SupplierEcosystemProfile | null>;
  create(supplierId: string): Promise<SupplierEcosystemProfile>;
  update(supplierId: string, patch: Partial<Omit<SupplierEcosystemProfile,'supplierId'|'createdAt'|'updatedAt'>>): Promise<SupplierEcosystemProfile | null>;
}

const fresh=(supplierId:string):SupplierEcosystemProfile=>{const now=new Date().toISOString();return {supplierId,status:'DRAFT',businessProfileComplete:false,serviceAreasComplete:false,categoriesComplete:false,evidenceComplete:false,termsAccepted:false,completedJobs:0,createdAt:now,updatedAt:now};};
export class MemorySupplierEcosystemRepository implements SupplierEcosystemRepository { private items=new Map<string,SupplierEcosystemProfile>(); async get(id:string){return this.items.get(id)??null;} async create(id:string){const existing=this.items.get(id);if(existing)return existing;const p=fresh(id);this.items.set(id,p);return p;} async update(id:string,patch:Partial<Omit<SupplierEcosystemProfile,'supplierId'|'createdAt'|'updatedAt'>>){const p=this.items.get(id);if(!p)return null;Object.assign(p,patch,{updatedAt:new Date().toISOString()});return p;} }

const map=(r:any):SupplierEcosystemProfile=>({supplierId:r.supplier_id,status:r.status,businessProfileComplete:r.business_profile_complete,serviceAreasComplete:r.service_areas_complete,categoriesComplete:r.categories_complete,evidenceComplete:r.evidence_complete,termsAccepted:r.terms_accepted,reputationScore:r.reputation_score??undefined,completedJobs:r.completed_jobs,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
export class PostgresSupplierEcosystemRepository implements SupplierEcosystemRepository { constructor(private readonly pool:Pool){} async get(id:string){const {rows}=await this.pool.query('SELECT * FROM supplier_ecosystem_profiles WHERE supplier_id=$1',[id]);return rows[0]?map(rows[0]):null;} async create(id:string){const {rows}=await this.pool.query("INSERT INTO supplier_ecosystem_profiles (supplier_id) VALUES ($1) ON CONFLICT (supplier_id) DO UPDATE SET updated_at=NOW() RETURNING *",[id]);return map(rows[0]);} async update(id:string,patch:Partial<Omit<SupplierEcosystemProfile,'supplierId'|'createdAt'|'updatedAt'>>){const cols:any={status:'status',businessProfileComplete:'business_profile_complete',serviceAreasComplete:'service_areas_complete',categoriesComplete:'categories_complete',evidenceComplete:'evidence_complete',termsAccepted:'terms_accepted',reputationScore:'reputation_score',completedJobs:'completed_jobs'};const fields:string[]=[];const values:any[]=[];let i=1;for(const [k,v] of Object.entries(patch)){if(cols[k]){fields.push(`${cols[k]}=$${i++}`);values.push(v);}}if(!fields.length)return this.get(id);values.push(id);const {rows}=await this.pool.query(`UPDATE supplier_ecosystem_profiles SET ${fields.join(',')},updated_at=NOW() WHERE supplier_id=$${i} RETURNING *`,values);return rows[0]?map(rows[0]):null;} }
