import type {Express,RequestHandler} from 'express';import {z} from 'zod';import {authenticatedPrincipal} from './authentication.js';import type {ListingRepository} from './listingRepository.js';import type {TransactionInterestRepository} from './transactionInterestRepository.js';
export function registerTransactionInterestRoutes(app:Express,auth:RequestHandler,listings:ListingRepository,repo:TransactionInterestRepository){
 app.post('/api/v1/buyer/listings/:listingId/interest',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='BUYER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const x=await listings.listPublic({});const listing=x.find(l=>l.id===req.params.listingId);if(!listing)return res.status(404).json({error:'LISTING_NOT_FOUND'});const body=z.object({message:z.string().max(2000).optional()}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'INVALID_INTEREST'});return res.status(201).json(await repo.createLead({listingId:listing.id,propertyId:listing.propertyId,buyerId:p.userId,status:'NEW',message:body.data.message,sellerId:listing.sellerId}));});
 app.post('/api/v1/buyer/leads/:leadId/viewings',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='BUYER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const lead=await repo.getLead(req.params.leadId,p.userId);if(!lead)return res.status(404).json({error:'LEAD_NOT_FOUND'});const body=z.object({requestedFor:z.string().datetime()}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'INVALID_VIEWING'});const listing=(await listings.listPublic({})).find(l=>l.id===lead.listingId);if(!listing)return res.status(404).json({error:'LISTING_NOT_FOUND'});return res.status(201).json(await repo.createViewing({...lead,leadId:lead.id,sellerId:listing.sellerId,requestedFor:body.data.requestedFor,status:'REQUESTED'}));});
 app.post('/api/v1/buyer/leads/:leadId/offers',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='BUYER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const lead=await repo.getLead(req.params.leadId,p.userId);if(!lead)return res.status(404).json({error:'LEAD_NOT_FOUND'});const body=z.object({amountCents:z.number().int().positive(),conditions:z.array(z.string().max(500)).max(20).default([])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'INVALID_OFFER'});return res.status(201).json(await repo.createOffer({...lead,leadId:lead.id,sellerId:(await listings.listPublic({})).find(l=>l.id===lead.listingId)?.sellerId,amountCents:body.data.amountCents,conditions:body.data.conditions,status:'SUBMITTED'}));});
 app.get('/api/v1/seller/leads',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});return res.json(await repo.listLeadsForSeller(p.userId));});
 app.get('/api/v1/seller/viewings',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});return res.json(await repo.listViewingsForSeller(p.userId));});
 app.get('/api/v1/seller/offers',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});return res.json(await repo.listOffersForSeller(p.userId));});
 app.post('/api/v1/seller/leads/:leadId/status',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const body=z.object({status:z.enum(['CONTACTED','QUALIFIED','VIEWING_REQUESTED','VIEWED','OFFERED','CLOSED','DECLINED'])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'INVALID_STATUS'});const x=await repo.updateLeadStatus(req.params.leadId,p.userId,body.data.status);return x?res.json(x):res.status(404).json({error:'LEAD_NOT_FOUND'});});
 app.post('/api/v1/seller/viewings/:viewingId/status',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const body=z.object({status:z.enum(['CONFIRMED','COMPLETED','CANCELLED'])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'INVALID_STATUS'});const x=await repo.updateViewingStatus(req.params.viewingId,p.userId,body.data.status);return x?res.json(x):res.status(404).json({error:'VIEWING_NOT_FOUND'});});
 app.post('/api/v1/seller/offers/:offerId/status',auth,async(req,res)=>{const p=authenticatedPrincipal(res);if(p.role!=='SELLER')return res.status(403).json({error:'ROLE_NOT_ALLOWED'});const body=z.object({status:z.enum(['UNDER_REVIEW','ACCEPTED','REJECTED','WITHDRAWN']),confirm:z.literal(true)}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'CONFIRMATION_REQUIRED'});const x=await repo.updateOfferStatus(req.params.offerId,p.userId,body.data.status);return x?res.json(x):res.status(404).json({error:'OFFER_NOT_FOUND'});});
}